#
# Makefile for the kernel FIM device drivers
#

obj-$(CONFIG_FIM_CORE)		+= fim.o
obj-$(CONFIG_FIM_ZERO_SERIAL)	+= serial/
obj-$(CONFIG_FIM_ZERO_SDIO)	+= sdio/
obj-$(CONFIG_FIM_ZERO_CAN)	+= can/
obj-$(CONFIG_FIM_ZERO_USB)	+= usb/
obj-$(CONFIG_FIM_ZERO_SPI)	+= spi/
obj-$(CONFIG_FIM_ONE_SERIAL)	+= serial/
obj-$(CONFIG_FIM_ONE_SDIO)	+= sdio/
obj-$(CONFIG_FIM_ONE_CAN)	+= can/
obj-$(CONFIG_FIM_ONE_USB)	+= usb/
obj-$(CONFIG_FIM_ONE_SPI)	+= spi/
