
mpiper-y := piper.o
mpiper-y += airoha.o
mpiper-y += digiDebug.o
mpiper-y += digiIsr.o
mpiper-y += digiTx.o
mpiper-y += digiRx.o
mpiper-y += digiMac80211.o
mpiper-y += piperDsp.o
mpiper-y += piperMacAssist.o
mpiper-y += phy.o
mpiper-y += adc121c027.o
mpiper-y += airohaCalibration.o
mpiper-y += digiPs.o
obj-$(CONFIG_DIGI_PIPER_WIFI) := mpiper.o

