#
# Makefile for pwm devices
#
obj-$(CONFIG_GENERIC_PWM) 	:= pwm.o

obj-$(CONFIG_ATMEL_PWM)		+= atmel-pwm.o
obj-$(CONFIG_NS921X_PWM)	+= ns9xxx-pwm.o
obj-$(CONFIG_S3C2443_PWM)	+= s3c24xx-pwm.o
obj-$(CONFIG_MXS_PWM)		+= mxs-pwm.o
